name: Deploy to Hostinger (SSH)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            SERVER_DIR="/home/USERNAME/mery"   # ← بدّل USERNAME لمسار حسابك على Hostinger
            BRANCH="main"

            mkdir -p "$SERVER_DIR"
            cd "$SERVER_DIR"

            if [ -z "$(ls -A "$SERVER_DIR" 2>/dev/null)" ]; then
              git clone --branch "$BRANCH" https://github.com/ahmednour1234/Merry.git .
            else
              git fetch origin
              git reset --hard "origin/$BRANCH"
            fi

            PHP_BIN="$(command -v php || echo /usr/bin/php)"
            COMPOSER_BIN="$(command -v composer || echo /usr/local/bin/composer || echo $HOME/bin/composer)"

            if [ ! -x "$COMPOSER_BIN" ]; then
              cd $HOME
              $PHP_BIN -r "copy('https://getcomposer.org/installer','composer-setup.php');"
              $PHP_BIN composer-setup.php
              mkdir -p "$HOME/bin"
              mv composer.phar "$HOME/bin/composer"
              echo 'export PATH="$HOME/bin:$PATH"' >> "$HOME/.bashrc"
              COMPOSER_BIN="$HOME/bin/composer"
              cd "$SERVER_DIR"
            fi

            export COMPOSER_MEMORY_LIMIT=-1
            export COMPOSER_ALLOW_SUPERUSER=1
            "$COMPOSER_BIN" install --no-dev --prefer-dist --optimize-autoloader

            $PHP_BIN artisan migrate --force
            $PHP_BIN artisan config:cache
            $PHP_BIN artisan route:cache
            $PHP_BIN artisan view:cache
            $PHP_BIN artisan storage:link || true

            find storage bootstrap/cache -type d -exec chmod 775 {} \;
            find storage bootstrap/cache -type f -exec chmod 664 {} \;
